version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - cd ./node_layers && npm install && cd ..
  pre_build:
    commands:
      # - npx tsc
      # - find ./artong -name "*.ts" -exec rm -rf {} \;
  build:
    commands:
      - serverless deploy