version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless@2
      - cd ./node_layers && npm install && cd ..
  build:
    commands:
      - serverless create-domain
      - serverless deploy