version: 0.1
phases:
  install:
    commands:
      - node -v
      - npm config set fetch-retry-mintimeout 20000
      - npm config set fetch-retry-maxtimeout 120000
      - npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
      - npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"
      - npm install
      - npm install -g serverless
      - cd ./node_layers && npm install && cd ..
  build:
    commands:
      - serverless create_domain --stage $ENV --param="s3_bucket=$S3_BUCKET"
      - serverless deploy --stage $ENV --param="s3_bucket=$S3_BUCKET"
