version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - cd ./node_layers && npm install && cd ..
  pre_build:
    commands:
      - node -v
      - nvm ls
      - export NODE_OPTIONS=--max_old_space_size=8192
  build:
    commands:
      - serverless create_domain
      - serverless deploy