version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - cd ./node_layers && npm install && cd ..
  build:
    commands:
      - serverless create_domain
      - serverless deploy