version: 0.1
phases:
  install:
    commands:
      - npm install
      - rm -rf node_modules/sharp
      - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp
      - npm install -g serverless
      - cd ./node_layers && npm install && cd ..
  build:
    commands:
      - serverless create_domain
      - serverless deploy